name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add other steps for building and testing your application...

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v7
